# This is a basic workflow to help you get started with Actions

name: Documentation Generation

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  convert_via_pandoc:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      ## Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
      #- run: echo "foo" > input.txt  # create an example file
      - name: Document Conversion
        uses: docker://pandoc/core:2.9
        with:
          args: "-s ./Documentation~/index.md -o ./Documentation~/index.html"
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: 'Add generated html'
          add: '*.html --force'
#          cwd: './pathToRepo/'


#jobs:
#  convert_via_pandoc:
#    runs-on: ubuntu-18.04
#    steps:
#      - uses: docker://pandoc/core:2.9
#        with:
#          args: "--help" # gets appended to pandoc command
# pandoc -s -o output.html input.txt
